=== gitschowos/ba-workspace/json/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "title": "Web form specification",
    "description": "A specification to describe a web form with all its technical details.",
    "type": "object",
    "required": [
        "content"
    ],
    "properties": {
        "title": {
            "description": "Overall title of the form",
            "type": "string"
        },
        "content": {
            "description": "Elements the form contains",
            "type": "array",
            "items": {
                "$ref": "#/definitions/formElement"
            }
        },
        "showClearButton": {
            "type": "boolean"
        },
        "showResetButton": {
            "type": "boolean"
        },
        "showExampleFiller": {
            "type": "boolean"
        }
    },
    "definitions": {
        "formElement": {
            "description": "Form elements",
            "type": "object",
            "properties": {
                "type": {
                    "description": "Type of the FormElement",
                    "enum": [
                        "group",
                        "input",
                        "checkbox",
                        "dropdown",
                        "radio",
                        "chiplist",
                        "table"
                    ]
                },
                "id": {
                    "description": "Unique identifier for this element",
                    "type": "string"
                },
                "label": {
                    "description": "Label displayed in the browser",
                    "type": "string"
                },
                "options": {
                    "description": "Additional options and parameters for this element",
                    "type": "object",
                    "properties": {
                        "activateCond": {
                            "description": "For conditional activating based on another element, specified by id",
                            "type": "string"
                        },
                        "displayCond": {
                            "description": "For conditional diyplaying based on another element, specified by id",
                            "type": "string"
                        }
                    }
                }
            },
            "required": [
                "id",
                "type"
            ],
            "allOf": [
                {
                    "if": {
                        "properties": {
                            "type": {
                                "const": "group"
                            }
                        },
                        "required": [
                            "type"
                        ]
                    },
                    "then": {
                        "properties": {
                            "options": {
                                "type": "object",
                                "properties": {
                                    "childs": {
                                        "type": "array",
                                        "items": {
                                            "$ref": "#/definitions/formElement"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "else": {
                        "properties": {
                            "options": {
                                "type": "object",
                                "properties": {
                                    "value": {
                                        "description": "Initial value of the element"
                                    },
                                    "styling": {
                                        "description": "String to define styling",
                                        "type": "string"
                                    },
                                    "required": {
                                        "description": "If the element is required for submitting the form",
                                        "type": "boolean"
                                    },
                                    "requiredErrorMessage": {
                                        "description": "Message shown field is required",
                                        "type": "string"
                                    },
                                    "exampleValue": {
                                        "description": "Value for example form filler"
                                    }
                                }
                            }
                        }
                    }
                },
                {
                    "if": {
                        "properties": {
                            "type": {
                                "const": "checkbox"
                            }
                        },
                        "required": [
                            "type"
                        ]
                    },
                    "then": {
                        "properties": {
                            "options": {
                                "type": "object",
                                "properties": {
                                    "showAsSwitch": {
                                        "description": "If a switch is displayed instead of a checkbox",
                                        "type": "boolean"
                                    }
                                }
                            }
                        }
                    }
                },
                {
                    "if": {
                        "properties": {
                            "type": {
                                "const": "input"
                            }
                        },
                        "required": [
                            "type"
                        ]
                    },
                    "then": {
                        "properties": {
                            "options": {
                                "type": "object",
                                "properties": {
                                    "inputType": {
                                        "description": "html type of the input field",
                                        "type": "string"
                                    },
                                    "placeholder": {
                                        "description": "Placeholder for the input field",
                                        "type": "string"
                                    },
                                    "autocomplete": {
                                        "description": "Values that should be suggested in an autocomplete menu",
                                        "$ref": "#/definitions/suggestionType"
                                    },
                                    "validatorRegex": {
                                        "description": "Regular expression the input value has to match to for a valid form",
                                        "type": "string"
                                    },
                                    "validatorErrorMessage": {
                                        "description": "Error Message, if the input does not match with the validatorRegex",
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                },
                {
                    "if": {
                        "properties": {
                            "type": {
                                "const": "radio"
                            }
                        },
                        "required": [
                            "type"
                        ]
                    },
                    "then": {
                        "properties": {
                            "options": {
                                "type": "object",
                                "properties": {
                                    "pickingOptions": {
                                        "description": "Availible radio options",
                                        "$ref": "#/definitions/suggestionType"
                                    }
                                },
                                "required": [
                                    "pickingOptions"
                                ]
                            }
                        }
                    }
                },
                {
                    "if": {
                        "properties": {
                            "type": {
                                "const": "dropdown"
                            }
                        },
                        "required": [
                            "type"
                        ]
                    },
                    "then": {
                        "properties": {
                            "options": {
                                "type": "object",
                                "properties": {
                                    "values": {
                                        "description": "Availible options to select",
                                        "$ref": "#/definitions/suggestionType"
                                    },
                                    "multiple": {
                                        "description": "If more than one value are selectable",
                                        "type": "boolean"
                                    }
                                },
                                "required": [
                                    "values"
                                ]
                            }
                        }
                    }
                },
                {
                    "if": {
                        "properties": {
                            "type": {
                                "const": "chiplist"
                            }
                        },
                        "required": [
                            "type"
                        ]
                    },
                    "then": {
                        "properties": {
                            "options": {
                                "type": "object",
                                "properties": {
                                    "suggestions": {
                                        "description": "Availible options to select",
                                        "$ref": "#/definitions/suggestionType"
                                    },
                                    "placeholder": {
                                        "description": "Placeholder for the field",
                                        "type": "string"
                                    },
                                    "removable": {
                                        "description": "If the added chips can be removed",
                                        "type": "boolean"
                                    },
                                    "onlySuggestions": {
                                        "description": "If only the suggestions can be added as chips",
                                        "type": "boolean"
                                    }
                                },
                                "required": [
                                    "suggestions"
                                ]
                            }
                        }
                    }
                },
                {
                    "if": {
                        "properties": {
                            "type": {
                                "const": "table"
                            }
                        },
                        "required": [
                            "type"
                        ]
                    },
                    "then": {
                        "properties": {
                            "options": {
                                "type": "object",
                                "properties": {
                                    "columns": {
                                        "description": "Elements that define the table",
                                        "type": "array",
                                        "items": {
                                            "$ref": "#/definitions/formElement"
                                        }
                                    },
                                    "deletable": {
                                        "description": "If the added table-rows can be deleted again",
                                        "type": "boolean"
                                    }
                                },
                                "required": [
                                    "columns"
                                ]
                            }
                        }
                    }
                }
            ]
        },
        "suggestionType": {
            "type": [
                "string",
                "array"
            ],
            "items": {
                "type": "string"
            }
        }
    }
}

=== gitschowos/ba-workspace/json/test-all.json
{
    "title": "Test of all supported elements",
    "content": [
        {
            "type": "group",
            "id": "checkboxes",
            "label": "Checkboxes",
            "options": {
                "childs": [
                    {
                        "type": "checkbox",
                        "id": "regular-checkbox",
                        "label": "Regular",
                        "options": {
                            "showAsSwitch": false,
                            "exampleValue": true
                        }
                    },
                    {
                        "type": "checkbox",
                        "id": "slider-checkbox",
                        "label": "As Slider",
                        "options": {
                            "showAsSwitch": true,
                            "exampleValue": false
                        }
                    },
                    {
                        "type": "checkbox",
                        "id": "regular-checkbox-activation",
                        "label": "Activated by Regular",
                        "options": {
                            "showAsSwitch": false,
                            "activateCond": "regular-checkbox"
                        }
                    },
                    {
                        "type": "checkbox",
                        "id": "slider-checkbox-activation",
                        "label": "Activated by Regular",
                        "options": {
                            "showAsSwitch": true,
                            "activateCond": "regular-checkbox"
                        }
                    },
                    {
                        "type": "checkbox",
                        "id": "regular-required-checkbox",
                        "label": "Required",
                        "options": {
                            "showAsSwitch": false
                        }
                    },
                    {
                        "type": "checkbox",
                        "id": "slider-required-checkbox",
                        "label": "Required",
                        "options": {
                            "showAsSwitch": true
                        }
                    }
                ]
            }
        },
        {
            "type": "group",
            "id": "radios",
            "label": "Radios",
            "options": {
                "childs": [
                    {
                        "type": "radio",
                        "id": "hardcoded-radio",
                        "label": "Hardcoded Radio",
                        "options": {
                            "pickingOptions": [
                                "Berlin",
                                "Hamburg",
                                "Hannover"
                            ],
                            "exampleValue":"Hamburg"
                        }
                    },
                    {
                        "type": "radio",
                        "id": "api-radio",
                        "label": "Radio from Api",
                        "options": {
                            "pickingOptions": "api/cities"
                        }
                    },
                    {
                        "type": "radio",
                        "id": "disabled-radio",
                        "label": "Activated by 'Hardcoded Radio'",
                        "options": {
                            "pickingOptions": [
                                "Berlin",
                                "Hamburg",
                                "Hannover"
                            ],
                            "activateCond": "hardcoded-radio"
                        }
                    },
                    {
                        "type": "radio",
                        "id": "required-radio",
                        "label": "Required",
                        "options": {
                            "pickingOptions": "api/engines",
                            "required": true
                        }
                    }
                ]
            }
        },
        {
            "type": "group",
            "id": "dropdowns",
            "label": "Dropdowns",
            "options": {
                "childs": [
                    {
                        "type": "dropdown",
                        "id": "hardcoded-dropdown",
                        "label": "Hardcoded Dropdown",
                        "options": {
                            "values": [
                                "Berlin",
                                "Hamburg",
                                "Hannover"
                            ],
                            "exampleValue":"Hamburg"
                        }
                    },
                    {
                        "type": "dropdown",
                        "id": "api-dropdown",
                        "label": "Dropdown from Api",
                        "options": {
                            "values": "api/cities"
                        }
                    },
                    {
                        "type": "dropdown",
                        "id": "disabled-dropdown",
                        "label": "Activated by Hardcoded Dropdown",
                        "options": {
                            "values": "api/cities",
                            "activateCond": "hardcoded-dropdown"
                        }
                    },
                    {
                        "type": "dropdown",
                        "id": "multiple-dropdown",
                        "label": "Dropdown with multiple selection",
                        "options": {
                            "values": [
                                "Berlin",
                                "Hamburg",
                                "Hannover"
                            ],
                            "multiple": true
                        }
                    },
                    {
                        "type": "dropdown",
                        "id": "multiple-dropdown-api",
                        "label": "Dropdown with multiple selection (from API)",
                        "options": {
                            "values": "api/cities",
                            "multiple": true
                        }
                    },
                    {
                        "type": "dropdown",
                        "id": "required-dropdown",
                        "label": "Required",
                        "options": {
                            "values": [
                                "Berlin",
                                "Hamburg",
                                "Hannover"
                            ],
                            "required": true
                        }
                    }
                ]
            }
        },
        {
            "type": "group",
            "id": "inputs",
            "label": "Inputs",
            "options": {
                "childs":[
                    {
                        "type":"input",
                        "id":"regular-input",
                        "label":"Regular Input",
                        "options":{
                            "exampleValue":"Beispieleingabe"
                        }
                    },
                    {
                        "type":"input",
                        "id":"with-placheholder",
                        "label":"With Placeholder",
                        "options":{
                            "placeholder":"Some example text"
                        }
                    },
                    {
                        "type":"input",
                        "id":"autocomplete-hardcoded",
                        "label":"Hardcoded Autocomplete",
                        "options":{
                            "autocomplete": [
                                "Berlin",
                                "Hamburg",
                                "Hannover"
                            ]
                        }
                    },
                    {
                        "type":"input",
                        "id":"autocomplete-api",
                        "label":"Autocomplete from api",
                        "options":{
                            "autocomplete": "api/cities"
                        }
                    },
                    {
                        "type":"input",
                        "id":"disabled-input",
                        "label":"Activated by Regular Input",
                        "options":{
                            "activateCond":"regular-input"
                        }
                    },
                    {
                        "type":"input",
                        "id":"required-input",
                        "label":"Required",
                        "options":{
                            "required":true
                        }
                    }
                ]
            }
        }
    ],
    "showClearButton": false,
    "showResetButton": true
}

=== gitschowos/ba-workspace/json/mobile-de.json
{
    "title": "Fahrzeugsuche",
    "content": [
        {
            "type": "group",
            "id": "zustand-auswahl",
            "label": "Fahrzeugzustand",
            "options": {
                "childs": [
                    {
                        "type": "checkbox",
                        "id": "neu",
                        "label": "Neu",
                        "options": {
                        }
                    },
                    {
                        "type": "checkbox",
                        "id": "gebraucht",
                        "label": "Gebraucht",
                        "options": {
                        }
                    }
                ]
            }
        },
        {
            "type": "group",
            "id": "modell-auswahl",
            "label": "Marke, Modell, Variante",
            "options":{
                "childs":[
                    {
                        "type": "input",
                        "id": "marke",
                        "label": "Marke",
                        "options":{
                            "inputType": "text",
                            "required": true,
                            "autocomplete": ["beliebig", "BMW", "Mercedes-Benz", "Audi", "Volkswagen", "Ford", "Tesla", "Toyota", "Porsche"]
                        }
                    },
                    {
                        "type": "input",
                        "id":"modell",
                        "label":"Modell",
                        "options":{
                            "inputType":"text",
                            "activateCond":"marke",
                            "required": false
                        }
                    },
                    {
                        "type": "input",
                        "id": "variante",
                        "label":"Variante",
                        "options": {
                            "inputType":"text",
                            "placeholder":"z. B. GTI ...",
                            "styling":"width: 100px"
                        }
                    }
                ]
            }
        },
        {
            "type":"group",
            "id":"typ-auswahl",
            "label":"Fahrzeugtyp",
            "options":{
                "childs":[
                    {
                        "type":"checkbox",
                        "id":"roadster",
                        "label":"Cabrio / Roadster",
                        "options":{}
                    },
                    {
                        "type":"checkbox",
                        "id":"kleinwagen",
                        "label":"Kleinwagen",
                        "options":{}
                    },
                    {
                        "type":"checkbox",
                        "id":"kombi",
                        "label":"Kombi",
                        "options":{}
                    },
                    {
                        "type":"checkbox",
                        "id":"limousine",
                        "label":"Limousine",
                        "options":{}
                    },
                    {
                        "type":"checkbox",
                        "id":"sportwagen",
                        "label":"Sportwagen / Coupè",
                        "options":{}
                    },
                    {
                        "type":"checkbox",
                        "id":"suv",
                        "label":"SUV / Geländewagen / Pickup",
                        "options":{}
                    },
                    {
                        "type":"checkbox",
                        "id":"van",
                        "label":"Van / Minibus",
                        "options":{}
                    },
                    {
                        "type":"checkbox",
                        "id":"andere",
                        "label":"Andere",
                        "value": true,
                        "options":{}
                    },
                    {
                        "type":"group",
                        "id":"sitzplaetze-auswahl",
                        "label":"Anzahl Sitzplätze",
                        "options":{
                            "displayCond":"van",
                            "childs":[
                                {
                                    "type":"input",
                                    "id":"sitzplatz-von",
                                    "label":"",
                                    "options":{
                                        "inputType":"number",
                                        "placeholder":"von",
                                        "autocomplete":["1", "2", "3"]
                                    }
                                },
                                {
                                    "type":"input",
                                    "id":"sitzplatz-bis",
                                    "label":"",
                                    "options":{
                                        "inputType":"number",
                                        "placeholder":"bis",
                                        "autocomplete":["4", "5", "6", "7", "8", "9"],
                                        "displayCond":"sitzplatz-von"
                                    }
                                }
                            ]
                        }
                    },
                    {
                        "type":"dropdown",
                        "id":"tueren",
                        "label":"Anzahl Türen",
                        "options":{
                            "values": ["2/3", "4/5", "6/7"],
                            "multiple":true
                        }
                    }
                ]
            }
        },
        {
            "type":"group",
            "id":"others",
            "label":"Weitere Optionen",
            "options":{
                "childs":[
                    {
                        "type":"input",
                        "id":"first-registration",
                        "label":"Erstzulassung ab",
                        "options":{
                            "inputType":"date"
                        }
                    },
                    {
                        "type":"radio",
                        "id":"engine",
                        "label":"Antriebsart",
                        "options":{
                            "pickingOptions":"api/engines"
                        }
                    }
                ]
            }
        }
    ],
    "showClearButton": false,
    "showResetButton": true
}
